services:
  backend:
    container_name: backend
    build: ./server
    environment:
      - DATABASE_URL=mongodb://mongo:27017/devices
    volumes:
      - ./server:/home/server
      - /home/server/node_modules
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    container_name: frontend
    build: ./client
    volumes:
      - ./client:/home/client
      - /home/client/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "3050:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./client/build:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local

